<a href="https://colab.research.google.com/github/Gustavo-Michael/Gustavo-Michael.github.io/blob/main/Mineria.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Minería de Datos

##Primer parcial

###Introducción

####Conceptos

* Minería de Datos: Es el proceso de obtención de grandes cantidades de información que sirve para identificar patrones y relaciones que no son notorios facilmente.
* Ciencia de datos: Es una rama que se basa en la estadistica, matemáticas, programación entre otras para poder obtener información de grandes cantidades de datos.



Help and Documentation in Python

In [ ]:
#La fumción help muestra ayuda de las funciones
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [ ]:
#otra forma es utilizando ? en las funciones
len?

In [ ]:
L = [1,2,3]
L.insert?

In [ ]:
#ejemplo de una función utilizando DotString
def square(a):
  """ Return the squre of a """
  return a ** 2

In [ ]:
square??

##Ciencia de Datos

In [1]:
 %timeit L = [n ** 2 for n in range(1000)]
#evalua el desempeño de una expresión en el tiempo

49.8 µs ± 1.27 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [4]:
#con %% podemos evaluar el desempeño en cuanto tiempo de más de una línea de codigo
%%timeit
L = []
for n in range(1000):
  L.append(n ** 2)

65.7 µs ± 17.1 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


##Ipython and Shell Commands

In [5]:
!ls #muestra los archivos contenidos en el directorio

sample_data


In [6]:
!pwd #con la exclamasión está en una microseción con % permanece

/content


In [8]:
!echo "hola mundo"

hola mundo


In [12]:
!print(directory)

/bin/bash: -c: line 1: syntax error near unexpected token `directory'
/bin/bash: -c: line 1: `print(directory)'


In [13]:
%cd /content

/content


In [14]:
%ls

sample_data/


In [15]:
%cd sample_data/

/content/sample_data


In [17]:
%ls

anscombe.json*                mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md*


In [18]:
%cat README.md #ayuda a visualizar un documento

This directory includes a few sample datasets to get you started.

*   `california_housing_data*.csv` is California housing data from the 1990 US
    Census; more information is available at:
    https://docs.google.com/document/d/e/2PACX-1vRhYtsvc5eOR2FWNCwaBiKL6suIOrxJig8LcSBbmCbyYsayia_DvPOOBlXZ4CAlQ5nlDD8kTaIDRwrN/pub

*   `mnist_*.csv` is a small sample of the
    [MNIST database](https://en.wikipedia.org/wiki/MNIST_database), which is
    described at: http://yann.lecun.com/exdb/mnist/

*   `anscombe.json` contains a copy of
    [Anscombe's quartet](https://en.wikipedia.org/wiki/Anscombe%27s_quartet); it
    was originally described in

    Anscombe, F. J. (1973). 'Graphs in Statistical Analysis'. American
    Statistician. 27 (1): 17-21. JSTOR 2682899.

    and our copy was prepared by the
    [vega_datasets library](https://github.com/altair-viz/vega_datasets/blob/4f67bdaad10f45e3549984e17e1b3088c731503d/vega_datasets/_data/anscombe.json).


## Tipos de Datos en Python

In [20]:
import numpy as np # numpy es una librería que crea arreglos de N dimensiones

In [22]:
#Arreglo lienal de enteros
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [23]:
#al ingresar enteros y flotantes los convierte en flotantes
np.array([3.14,4,2,3.0])


array([3.14, 4.  , 2.  , 3.  ])

In [24]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [26]:
np.array([1, 2, 3, 4], dtype='int')

array([1, 2, 3, 4])

In [30]:
#cuando el argumento de np.array es una iteracióm anidada genera una matriz
np.array([range(i, i + 3) for i in [2, 4, 6]])
#The inner lists are treated as rows of the resulting two-dimensional array.

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])